version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform:
   - x64
   - x86

clone_depth: 2

install:
- cmd: git submodule update --init --recursive

build_script:
- cmd: >-
    CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

    cmake -G "NMake Makefiles" .

    nmake

    ctest -V
