version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform:
   - x64
   - x86

clone_depth: 2

install:
- cmd: git submodule update --init --recursive

build_script:
- cmd: >-
    cmake -G "NMake Makefiles" .

    nmake

    ctest -V
