language: cpp

os:
  - linux
  - osx

dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-10

before_script:
  - case "$TRAVIS_OS_NAME-$CXX" in
    linux-g++) export CXX=g++-10 CC=gcc-10;;
    esac
  - $CXX --version
  - cmake --version

script:
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make -j2

notifications:
  email: false

# vim: sw=2 et
