language: cpp

os:
  - linux
  - osx

# Linux should use the "newer" 14.04 release (12.04 is default)
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_script:
  - case "$TRAVIS_OS_NAME-$CXX" in
    linux-g++) export CXX=g++-6 CC=gcc-6;;
    esac
  - $CXX --version
  - cmake --version

script:
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make -j2

notifications:
  email: false

# vim: sw=2 et
